function stateNext = stateModel(state,dt)
% Define the state transition matrix;
%cambiare Ts(metterlo costante ricompianare)
F=[1 0 dt*cos(state(4)) 0;...
    0 1 dt*sin(state(4)) 0;...
    0 0 1 0;...
    0 0  0 1;];
G=[cos(state(4))*dt^2/2 0;...
      sin(state(4))*dt^2/2 0;...
      dt                                  0;...
      0                                   dt;];

stateNext = F*state(1:4)+G*state(5:6);
stateNext=[stateNext;state(5:6)];
end